# Site Settings
title: SuperSlamZzz的博客
email: zhuchun92@163.com
description: 2019年07月11日坐标武汉，开始整理我的知识库.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://superslamzzz.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: SuperSlamZzz~
user_description: ITer.
disqus_username: disqus_username是啥

# Social Media
# Remove the item if you don't need it
github_username: SuperSlamZzz
facebook_username: Nouse
twitter_username: Nouse
instagram_username: Nouse
linkedin_username: Nouse
medium_username: Nouse

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 主页
    url: /
  - title: 关于博客
    url: /about/
  - title: 联系我
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
